name: wipap
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  http: ^0.12.0+4
  flutter_spinkit: ^4.1.2
  font_awesome_flutter: ^8.8.1
  flutter_bloc: ^4.0.0
  google_maps_flutter: ^0.5.26+4
  location: ^3.0.2
  geolocation: ^1.1.2
  search_map_place: ^0.3.0
  shared_preferences: ^0.5.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


  uses-material-design: true


  assets:
    - images/

  # fonts:
  # - family: Pacifico
  #   fonts:
  #   - asset: fonts/Pacifico-Regular.ttf

  # - family: Source Sans Pro
  #   fonts:
  #   - asset: fonts/SourceSansPro-Regular.ttf